export default [{
    ItemName : "Product1",
    price: 13000,
    img : "@/assets/product.png",
    discount : true,
    discountRate: 30,
    },
    {
    ItemName : "Product2",
    price: 13000,
    img : "@/assets/product.png",
    discount : false,
    discountRate: '',
    },
    {
    ItemName : "Product3",
    price: 13000,
    img : "@/assets/product.png",
    discount : false,
    discountRate: '',
    },
    {
    ItemName : "Product4",
    price: 13000,
    img : "@/assets/product.png",
    discount : false,
    discountRate: '',
    },
    {
    ItemName : "Product5",
    price: 13000,
    img : "@/assets/product.png",
    discount : false,
    discountRate: '',
    },
    {
    ItemName : "Product6",
    price: 13000,
    img : "@/assets/product.png",
    discount : false,
    discountRate: '',
    },
]