export default [{
  ItemName: 'Product1',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: true,
  discountRate: 30,
},
{
  ItemName: 'Product2',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product3',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product4',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product5',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product6',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product7',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
{
  ItemName: 'Product8',
  price: 13000,
  image: 'https://s3.ap-northeast-2.amazonaws.com/storage.b-flow.io/9717102/conversions/resize.jpg',
  discount: false,
  discountRate: '',
},
];
